### ISSUE TITLE
Add -usbdevice tablet for trackpad support

### ISSUE THREAD

**Issue by mpolek** [adespoton/utmconfigs#1]
When attempting to boot a BaseSystem.dmg to install Mojave, the screen would show a picture of the underside of a bluetooth magic mouse telling me to turn it on. Once I added -usbdevice tablet (in addition to -usbdevice keyboard) to the qemu command line, the recovery image started up.

**Comment by adespoton** [comment]
I've added -usbdevice tablet to the configs now.  It's possible this might break things for people with no trackpad, but I'm guessing the majority of M1 users have a trackpad.
