### ISSUE TITLE
macOS 11 not installing

### ISSUE THREAD

**Issue by stossy11** [adespoton/utmconfigs#11]
So I'm trying to install macOS 11 on my M1 iPad Air and it is not working it freezes on less than a minute remaining and is not going past that I've left if for a whole night and haven't been able to fix it

**Comment by stossy11** [comment]
I am going try it on my Mac then transfer it to my ipad

**Comment by stossy11** [comment]
I just had to downgrade the version from 11.7.1 to 11.6.1

**Comment by stossy11** [comment]
it is soooo slow to the point where you cant get past the first phase in setuo

**Comment by stossy11** [comment]
but it boots

**Comment by adespoton** [comment]
Changing your storage device type may help speed things up.  It’s not going to become what I’d call usable though.-Em On Dec 7, 2022, at 12:44 PM, stossy11 ***@***.***> wrote:﻿
but it boots
