### ISSUE TITLE
Problem with Mojave

### ISSUE THREAD

**Issue by mauromarzocca** [adespoton/utmconfigs#14]
Hi, I try to install MacOS Mojave, but I haven't the installer. I download it from fetch Mac OS.
![Screenshot 2023-04-26 alle 18 41 49](https://user-images.githubusercontent.com/57107500/234645103-6b2e5f76-d505-4cb8-a83e-cb07b31051f4.png)

**Comment by MacDada** [comment]
how did you fix it?
