### ISSUE TITLE
Mac OS X 10.4.7 Server getting stuck when trying to load the Extensions.kext

### ISSUE THREAD

**Issue by UrkiMimi** [adespoton/utmconfigs#17]
Pretty much what it says in the title. Host is a iMac M1 2021 on macOS Sonoma DP5. UTM version is 4.3.5.

<img width="1392" alt="Screenshot 2023-08-12 at 1 36 17 AM" src="https://github.com/adespoton/utmconfigs/assets/74517821/c678df31-29ca-4a59-be93-a8596ff4918e">
Screenshot where it got stuck at and config.

[Mac OS X 10.4 Server Config.utm.zip](https://github.com/adespoton/utmconfigs/files/12326752/Mac.OS.X.10.4.Server.Config.utm.zip)

**Comment by adespoton** [comment]
I’m not sure what you did there, but the 10.4 Server config is for PPC, and you appear to be trying to load Intel power management kexts?  Are you using an Intel-only 10.4.7 installer?-Em On Aug 11, 2023, at 11:41 PM, UrkiMii ***@***.***> wrote:﻿
Pretty much what it says in the title. Host is a iMac M1 2021 on macOS Sonoma DP5. UTM version is 4.3.5.

Screenshot where it got stuck at and config.
[Mac OS X 10.4 Server Config.utm.zip](https://github.com/adespoton/utmconfigs/files/12326750/Mac.OS.X.10.4.Server.Config.utm.zip)

**Comment by UrkiMimi** [comment]
The config I am using is a heavily modified version of the OS X 10.7 config. The installer I am using for this is a universal installer found on [archive.org.](https://archive.org/download/Macintosh_Garden_OS_Collection/Mac_OS_X_Server_10.4.7_universal.dmg)

**Comment by adespoton** [comment]
In that case, I’m not sure why you filed an issue?  My page clearly states that Intel 10.4-10.6 aren’t working, and I haven’t provided configs for them.If you can figure out how to tweak the 32-bit OpenCore package to work with these versions, feel free to submit a pull request with the working configs.-Em On Aug 12, 2023, at 12:46 PM, UrkiMii ***@***.***> wrote:﻿
The config I am using is a heavily modified version of the OS X 10.7 config. The installer I am using for this is a universal installer found on archive.org.
