### ISSUE TITLE
Changing display resolution

### ISSUE THREAD

**Issue by mavrothal** [adespoton/utmconfigs#20]
I managed to get os x 10.9 running on an M1 mac using the VMware image as [suggested.](https://github.com/adespoton/utmconfigs/issues/7#issuecomment-1249984697)
Thank you.
I'm trying now to change screen resolution to something bigger than the default 1280 x 720, as some of the apps I try to keep using, require at least a 1440 x 900 display, but I cannot find a way to do it (Changing emulated cards also had no effect - other than failing some)
I understand the SPICE tools are not available for osx guests, so resizing the window cannot  change resolution. So I was wondering if it would be possible in some other way in the UTM config to change the default display resolution.

Thank you for making possible to run old OSX versions and  apps under Apple silicon

**Comment by LukasAppleFan** [comment]
Yeah I was wondering the same. I tried with Mac OS X Lion on my end and just can't figure how to change the resolution. For instance I was able to change the resolution on my other 10.2 Jaguar VM just fine from Mac OS X itself

**Comment by adespoton** [comment]
Odd; changing from inside the OS should work for 10.7 and 10.9 as well.  The difference is in the X86-64 emulator I haven’t found a way to introduce custom screen resolutions without modifying the EFI configuration.  To do that, you need to show in Finder, quit UTM, convert the EFI image from qcow2 to raw, mount it on your host, edit the config.xml file to change the resolution, unmount the image, convert back to qcow2 and overwrite the existing file with your modified one.Of course if you can do all that it’s only baby steps to compiling your own QEMU and OVMF and not using UTM in the first place.-Em On Dec 29, 2023, at 3:29 AM, Lukas ***@***.***> wrote:﻿
Yeah I was wondering the same. I tried with Mac OS X Lion on my end and just can't figure how to change the resolution. For instance I was able to change the resolution on my other 10.2 Jaguar VM just fine from Mac OS X itself

**Comment by LukasAppleFan** [comment]
Hi, thanks for your reply but I can't find a way to change the resolution. I mounted the RAW image but couldn't find the file.
There is also a config file in the UTM file but it's a plist.


<img width="918" alt="Capture d’écran 2024-01-02 à 21 10 19" src="https://github.com/adespoton/utmconfigs/assets/41242166/d9c4b429-3d72-489f-a63f-91ef727212e4">

<img width="914" alt="Capture d’écran 2024-01-02 à 21 11 05" src="https://github.com/adespoton/utmconfigs/assets/41242166/a1ae78c3-462d-4558-af19-a660a3e19389">

Thanks in advance

**Comment by adespoton** [comment]
The plist is the xml file I was referring to; sorry, forgot it had a .plist extension.-Em On Jan 2, 2024, at 12:11 PM, Lukas ***@***.***> wrote:﻿
Hi, thanks for your reply but I can't find a way to change the resolution. I mounted the RAW image but couldn't find the file.
There is also a config file in the UTM file but it's a plist.
Capture.d.ecran.2024-01-02.a.21.10.19.png (view on web)
Capture.d.ecran.2024-01-02.a.21.11.05.png (view on web)
Thanks in advance

**Comment by mavrothal** [comment]
> Hi, thanks for your reply but I can't find a way to change the resolution. I mounted the RAW image but couldn't find the file. There is also a config file in the UTM file but it's a plist.
> 

The plist you want to edit is in 'OS X...utm>Data>EFI-LEGACY.qcow2'. Specifically the UEFI>Output>Resolution string.
I used 
```
qemu-img convert  EFI-LEGACY.qcow2 EFI.raw
hdiutil attach -imagekey diskimage-class=CRawDiskImage EFI.raw
# edit plist
qemu-img convert  EFI.raw EFI-LEGACY.qcow2
```

**Comment by LukasAppleFan** [comment]
Not sure what I did wrong but I tried "2880 by 1800 pixels (Retina); scaled resolutions: 1920 by 1200" from Mactracker and I got this :

<img width="442" alt="Capture d’écran 2024-01-03 à 18 18 12" src="https://github.com/adespoton/utmconfigs/assets/41242166/0f788995-f470-4eda-9088-68f228888914">

**Comment by mavrothal** [comment]
> Not sure what I did wrong but I tried "2880 by 1800 pixels (Retina); scaled resolutions: 1920 by 1200" from Mactracker and I got this

Try something more modest to make sure that you can change things. 
1440x900 works for me in OSX 10.9
Besides with 4MB VARM that the virtual machine has, even 1440x900 is painful.
