### ISSUE TITLE
Cannot Boot from ISO, stuck on "No valid state has been set by load or init-program"

### ISSUE THREAD

**Issue by mihirpotnis** [adespoton/utmconfigs#23]
So whether I download the configs or recreate the config, I cannot boot from the ISO to start the MacOS X install.

I thought maybe this was an issue with UTM 4 so I downgraded to UTM 3 but still the same problem.

<img width="798" alt="Screenshot 2023-11-05 at 11 37 20 AM" src="https://github.com/adespoton/utmconfigs/assets/103370170/bbfdeda1-1058-4de4-852c-9bbeb598aece">

I get stuck at "No valid state has been set by load or init-program"

I'm on MacBook Pro M1 Max, running Sonoma

**Comment by barracuda156** [comment]
Same thing. MacBook Air M1 with Sonoma, Leopard 10.5.6 PPC ISO, yellow screen -_-

**Comment by mihirpotnis** [comment]
Ok so I did figure out what the problem is. 

If UTM says "No valid state has been set by load or init program" it is most definitely the dmg/iso.

It's not bootable, just keep trying different iso's/dmg's until it boots.
