### ISSUE TITLE
How to setup 10.2 and 10.3 with multiple CD's

### ISSUE THREAD

**Issue by mihirpotnis** [adespoton/utmconfigs#24]
So for Jaguar and Panther, there are multiple discs but when you set up only the first disc is bootable, the second disc doesn't boot and the installation after the first disc doesn't boot from the virtual HDD either.

Has anyone been able to get through this issue?

**Comment by adespoton** [comment]
I’ve just used the install DVD, not the CDs.But it should still be possible using the CDs by ejecting the first image and “inserting” the next when prompted.-Em On Nov 19, 2023, at 3:29 AM, mihirpotnis ***@***.***> wrote:﻿
So for Jaguar and Panther, there are multiple discs but when you set up only the first disc is bootable, the second disc doesn't boot and the installation after the first disc doesn't boot from the virtual HDD either.
Has anyone been able to get through this issue?

**Comment by mihirpotnis** [comment]
Ah yes, I figured out that the boot order has to be setup as HDD first, then CD and then the installation will continue.

Thanks
