### ISSUE TITLE
OS X 10.5 PPC Install fails when trying to set boot disk

### ISSUE THREAD

**Issue by gkra** [adespoton/utmconfigs#29]
Using the "OS X 10.5 PPC" config in UTM 4.4.4(93), at the very end of the install process, the screen is an error message:

> Mac OS X could not be installed on your computer
> 
> The Installer could not make the computer start up from the volume "Macintosh HD". You may need to select your disk using the Startup Disk utility.

Opening the install log window, I see the following:

```
392454 Mar 29 13:31:32 localhost Unknown [66]: 2824-03-29 13:31:32.656 bless [4907:10b] _CFGetHöstUUIDString: unable to determine UUID for host. Error: 35
392455 Mar 29 13:31:33 localhost Unknown [66]: nvram: Error (-1) getting variable - 'boot-args '
392456 Mar 29 13:31:38 localhost OSInstaller [130]: Unable to set 'Macintosh HD ' as boot disk
392457 Mar 29 13:31:38 localhost 0SInstaller [130]: Install failed: The Installer could not make the computer start up from the Installer could not make the computer start up from the volume "Macintosh HD". You may need to select your disk using the Startup Disk utility.
394067 Mar 29 13:31:38 localhost ReportCrash[4909]: Could not save crash report to disk!
394068 Mar 29 13:31:39 localhost ReportCrash[4909]: Process: bless [4907]
394069 Mar 29 13:31:39 localhost ReportCrash[4909]: Path: /usr/sbin/bless
394070 Mar 29 13:31:39 localhost ReportCrash[4909]: Identifier: bless
394071 Mar 29 13:31:39 localhost ReportCrash[4909]: Version: ??? (???)
394072 Mar 29 13:31:39 localhost ReportCrash[4909]: Code Type: PPC (Native)
394073 Mar 29 13:31:39 localhost ReportCrash[4909]: Parent Process: DiskManagement Tool [132]
394074 Mar 29 13:31:39 localhost ReportCrash[4909]:
394075 Mar 29 13:31:39 localhost ReportCrash[4909]: Date/Time: 2024-03-29 13:31:33.255 -0700
394076 Mar 29 13:31:39 localhost ReportCrash[4909]: 0S Version: Mac OS X 10.5 (94581)
394077 Mar 29 13:31:39 localhost ReportCrash[4909]: Report Version: 6
394078 Mar 29 13:31:39 localhost ReportCrash[4909]:
394079 Mar 29 13:31:39 localhost ReportCrash[4909]: Exception Type: EXC_BAD_ACCESS (SIGBUS)
394080 Mar 29 13:31:39 localhost ReportCrash[4909]: Exception Codes: KERN_PROTECTION_FAILURE at 0x0000000000000000
394081 Mar 29 13:31:39 localhost ReportCrash[4909]: Crashed Thread: 0
394082 Mar 29 13:31:39 localhost ReportCrash[4909]:
394083 Mar 29 13:31:39 localhost ReportCrash[4909]: Thread @ Crashed:
394084 Mar 29 13:31:39 localhost ReportCrash[4909]: 0 libSystem.B.dylib 0x0050a128 strlen + 8
394085 Mar 29 13:31:39 localhost ReportCrash[4909]:
394086 Mar 29 13:31:39 localhost ReportCrash[4909]: Thread 0 crashed with PPC Thread State 32:
394087 Mar 29 13:31:39 localhost ReportCrash[4909]: srr0: 0x00500128 srr1: 0x0000f030 dar: 0x00000000 dsisr: 0x40000000
394088 Mar 29 13:31:39 localhost ReportCrash[4909]: r0: 0x00000000 r1: 0xbfffcdc0 r2: 0x00013ff2 r3: 0x00000000
394089 Mar 29 13:31:39 localhost ReportCrash[4909]: r4: 0x00013ff0 r5: 0x00000008 r6: 0x00000afc r7: 0xffffffff
394090 Mar 29 13:31:39 localhost ReportCrash[4909]: 18: 0xbfffedfc r9: 0x00000000 r10: 0xbfffd618 r11: 0x0001750
394091 Mar 29 13:31:39 localhost ReportCrash[4909]: r12: 0x00500120 r13: 0x00000000 r14: 0x00000000 r15: 0x00000000
394092 Mar 29 13:31:39 localhost ReportCrash[4909]: r16: 0x00000000 117: 0x00000000 r18: 0x00000000 r19: 0x00000000
394093 Mar 29 13:31:39 localhost ReportCrash[4909]: r20: 0x00000000 r21: 0x00000000 r22: 0x00000000 r23: 0x00000001
394094 Mar 29 13:31:39 localhost ReportCrash[4909]: r24: 0x00010140 r25: 0xbfffd218 r26: 0x00028154 r27: 0xbfffd618
394095 Mar 29 13:31:39 localhost ReportCrash[4909]: r28: 0xbfffce18 r29: 0x00000000 r30: 0xbffffcb4 r31: 0x0000014c
394096 Mar 29 13:31:39 localhost ReportCrash[4909]: cr: 0x42000228 xer: 0x00000002 Ir: 0x00000260 ctr: 0x0050a120
394097 Mar 29 13:31:39 localhost ReportCrash[4909]: vrsave: 0x00000000
394098 Mar 29 13:31:39 localhost ReportCrash[4909]:
394099 Mar 29 13:31:39 localhost ReportCrash[4909]: Binary Images:
```

This is then followed by a long list of debugging info that I wasn't able to scrape off the VM screen in any easy way.

So, it appears the failure is that `bless` is looking to (possibly retrieve, and then) write some info into nvram, which exists on Mac hardware, but possibly not in qemu? 

I'm genuinely at a loss here as I'm mainly a power user trying to set up a PPC OS X Leopard VM so I can get this Mac Mini G4 off my desk, but I'm happy to experiment under direction.

Screenshots of the failure:

![Screenshot 2024-03-29 at 20 48 10](https://github.com/adespoton/utmconfigs/assets/3741190/534a8281-6972-4a90-af41-88c95647a4d1)

![Screenshot 2024-03-29 at 20 49 34](https://github.com/adespoton/utmconfigs/assets/3741190/99f20fe6-068f-4e4e-b040-f83c9b5b5fd2)

**Comment by gkra** [comment]
Found the "solution", or at least a workaround, here:

https://www.emaculation.com/forum/viewtopic.php?t=10784

Basically, at the "Installation Failed" screen, select the Utilities menu, then choose "Startup Disk", select the drive you just installed Mac OS X to, and restart.

Once you see it shut down, power the VM off, edit it, and select the IDE device for the CDROM, right-click on it, and "Move down".

Now you can restart the VM and it'll boot into your fresh OS X Leopard install.

**Comment by adespoton** [comment]
That’s also in the instructions in the 10.5 UTM config isn’t it?-Em On Mar 29, 2024, at 11:44 PM, Gregory Ruiz-Ade ***@***.***> wrote:﻿
Found the "solution", or at least a workaround, here:
https://www.emaculation.com/forum/viewtopic.php?t=10784
Basically, at the "Installation Failed" screen, select the Utilities menu, then choose "Startup Disk", select the drive you just installed Mac OS X to, and restart.
Once you see it shut down, power the VM off, edit it, and select the IDE device for the CDROM, right-click on it, and "Move down".
Now you can restart the VM and it'll boot into your fresh OS X Leopard install.
