### ISSUE TITLE
File Sharing With 10.7

### ISSUE THREAD

**Issue by jplwoodward** [adespoton/utmconfigs#34]
I managed to get 10.7 running on my M3.  I cannot get 10.8 - 10.13 to run for various reasons.  However, file sharing does not work. I turned it on, and the guest 10.7 shows up when I look at Network on my M3, but connecting to it says it does not exist.  Is this a known issue?  Am I missing something?  Without file sharing I cannot get the Application I need to run into 10.7 nor get results back.

**Comment by adespoton** [comment]
There are no file sharing drivers for OS X before macOS 10.14.7.  You can convert the images to DMG and mount them on the host or do SMB or other network based filesharing.There is a driver you can add to Mac OS 9 that works with UTM’s filesharing feature.-Em On Jul 14, 2024, at 1:08 PM, jplwoodward ***@***.***> wrote:﻿
I managed to get 10.7 running on my M3.  I cannot get 10.8 - 10.13 to run for various reasons.  However, file sharing does not work. I turned it on, and the guest 10.7 shows up when I look at Network on my M3, but connecting to it says it does not exist.  Is this a known issue?  Am I missing something?  Without file sharing I cannot get the Application I need to run into 10.7 nor get results back.

**Comment by danielvonmitschke** [comment]
> There are no file sharing drivers for OS X before macOS 10.14.7.  

There is nothing like 10.14.7.
10.14.6 was the last version
