### ISSUE TITLE
Ventura support

### ISSUE THREAD

**Issue by dmatora** [adespoton/utmconfigs#35]
What about Ventura support?
This could be used as foundation https://www.nicksherlock.com/2022/10/installing-macos-13-ventura-on-proxmox/

**Comment by adespoton** [comment]
I’m not planning to add UTM emulator configs higher than macOS 11, as virtualization is a much superior solution, and fully supported by UTM out of the box.-Em On Jul 31, 2024, at 5:14 AM, dmatora ***@***.***> wrote:﻿
What about Ventura support?
This could be used as foundation https://www.nicksherlock.com/2022/10/installing-macos-13-ventura-on-proxmox/

**Comment by dmatora** [comment]
it's only supported for Apple Silicon, Intel Macs require configs.
Btw, spent entire day yesterday trying to boot at least 1 config on my Intel iMac and none worked (best case macOS install doesn't finish booting - hanging or crashing)
Was this ever supposed to work on x86?

**Comment by adespoton** [comment]
If you’re on x86, there are way better options.  QEMU does instruction pass-through on x86, so you can use any virtual machine including UTM to run OS X x86.  My configs would only be useful for Mac OS 9.0.4 through OS X 10.5 PPC.You could modify the configs to explicitly use the TCG emulator, but the performance hit wouldn’t be worthwhile.-Em On Jul 31, 2024, at 8:05 PM, dmatora ***@***.***> wrote:﻿
it's only supported for Apple Silicon, Intel Macs require configs.
Btw, spent entire day yesterday trying to boot at least 1 config on my Intel iMac and none worked (best case macOS install doesn't finish booting - hanging or crashing)
Was this ever supposed to work on x86?

**Comment by dmatora** [comment]
> EMU does instruction pass-through on x86, so you can use any virtual machine including UTM to run OS X x86
Any hint how?
I've tried setting up new VM using Proxmox OpenCore images, and managed to boot install, but macOS hangs for about 20 minutes before it boots, and I haven't managed to boot installed macOS yet at all.

**Comment by adespoton** [comment]
This is outside the scope of UTM OS X configs.
