### ISSUE TITLE
10.6 to 10.11 configs missing

### ISSUE THREAD

**Issue by nalsuriv** [adespoton/utmconfigs#40]
The configuration files to virtualize Intel Mac OS X, versions:

- 10.6 Snow Leopard (2008);
- 10.7 Lion (2010);
- 10.8 Mountain Lion (2012);
- 10.9 Mavericks (2013);
- 10.10 Yosemite (2014);
- 10.11 El Capitan (2015);

— are missing.

**Comment by adespoton** [comment]
From where? I see the zip files still sitting there?

**Comment by nalsuriv** [comment]
I stand corrected. Still, I am unable to see these configs:
10.6
10.10
10.11.
Perhaps, you forgot to add these particular zip files?

**Comment by adespoton** [comment]
There's no config for 10.6, as it needs a bunch of custom work to boot in UTM.  I'm still working on configs that will just "run" for Mac OS 7.1 - 8.1, for OS X 10.4 x86, for 10.5 x86 and 10.6 x86.  They all work now in vanilla QEMU, but UTM overrides some of the default settings that are needed.

All this is in the Readme.

The other configs are all there; maybe you're confused by the change in name between Mac OS X and OS X?  It means that they aren't listed in order of release.

[Mac OS 9.1 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/Mac%20OS%209.1%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[Mac OS 9.2.1 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/Mac%20OS%209.2.1%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[Mac OS 9.2.2 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/Mac%20OS%209.2.2%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[OS X 10 Public Beta (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010%20Public%20Beta%20(config%20only).utm.zip)
	
[Add OS X PB](https://github.com/adespoton/utmconfigs/commit/b38154098ce58babbc9d6de514e31d6f4648ac7e)
	
Feb 25, 2022
[OS X 10.0 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010.0%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[OS X 10.1 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010.1%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[OS X 10.10 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010.10%20(config%20only).utm.zip)
	
[Add/update configs](https://github.com/adespoton/utmconfigs/commit/704e7c644daeca8c44a57ca8d584662321db668f)
	
Feb 22, 2022
[OS X 10.11 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010.11%20(config%20only).utm.zip)
	
[Add/update configs](https://github.com/adespoton/utmconfigs/commit/704e7c644daeca8c44a57ca8d584662321db668f)
	
Feb 22, 2022
[OS X 10.2 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010.2%20(config%20only).utm.zip)
	
[Update OS X 10.2 (config only).utm.zip](https://github.com/adespoton/utmconfigs/commit/9cc1b37fda418f6ad5840e826956ece12ab2396c)
	
May 4, 2024
[OS X 10.3 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010.3%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[OS X 10.4 PPC (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010.4%20PPC%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[OS X 10.5 PPC (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010.5%20PPC%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[OS X 10.7 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010.7%20(config%20only).utm.zip)
	
[Add/update configs](https://github.com/adespoton/utmconfigs/commit/704e7c644daeca8c44a57ca8d584662321db668f)
	
Feb 22, 2022
[OS X 10.8 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010.8%20(config%20only).utm.zip)
	
[Add/update configs](https://github.com/adespoton/utmconfigs/commit/704e7c644daeca8c44a57ca8d584662321db668f)
	
Feb 22, 2022
[OS X 10.9 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%2010.9%20(config%20only).utm.zip)
	
[Add/update configs](https://github.com/adespoton/utmconfigs/commit/704e7c644daeca8c44a57ca8d584662321db668f)
	
Feb 22, 2022
[OS X Server 10.0 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%20Server%2010.0%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[OS X Server 10.1 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%20Server%2010.1%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[OS X Server 10.2 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%20Server%2010.2%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[OS X Server 10.3 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%20Server%2010.3%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[OS X Server 10.4 PPC (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%20Server%2010.4%20PPC%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[OS X Server 10.5 PPC (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/OS%20X%20Server%2010.5%20PPC%20(config%20only).utm.zip)
	
[Add Mac OS 9.1 - Mac OS X 10.5 PPC, OS X 10.7](https://github.com/adespoton/utmconfigs/commit/b99957a49c3bb96a9c109dee056891bb2ccfa461)
	
Feb 20, 2022
[README.md](https://github.com/adespoton/utmconfigs/blob/main/README.md)
	
[Update README.md](https://github.com/adespoton/utmconfigs/commit/0816381bfa503c2a67d5849195895041407c8cea)
	
Nov 17, 2024
[macOS 10.12 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/macOS%2010.12%20(config%20only).utm.zip)
	
[Add/update configs](https://github.com/adespoton/utmconfigs/commit/704e7c644daeca8c44a57ca8d584662321db668f)
	
Feb 22, 2022
[macOS 10.13 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/macOS%2010.13%20(config%20only).utm.zip)
	
[Add/update configs](https://github.com/adespoton/utmconfigs/commit/704e7c644daeca8c44a57ca8d584662321db668f)
	
Feb 22, 2022
[macOS 10.14 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/macOS%2010.14%20(config%20only).utm.zip)
	
[Add/update configs](https://github.com/adespoton/utmconfigs/commit/704e7c644daeca8c44a57ca8d584662321db668f)
	
Feb 22, 2022
[macOS 10.15 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/macOS%2010.15%20(config%20only).utm.zip)
	
[Add/update configs](https://github.com/adespoton/utmconfigs/commit/704e7c644daeca8c44a57ca8d584662321db668f)
	
Feb 22, 2022
[macOS 11 X86-64 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/macOS%2011%20X86-64%20(config%20only).utm.zip)
	
[Add/update configs](https://github.com/adespoton/utmconfigs/commit/704e7c644daeca8c44a57ca8d584662321db668f)
	
Feb 22, 2022
[macOS 12 X86-64 (config only).utm.zip](https://github.com/adespoton/utmconfigs/blob/main/macOS%2012%20X86-64%20(config%20only).utm.zip)
	
[Add native UTM links to README](https://github.com/adespoton/utmconfigs/commit/bd3b077cc17103b6978476fa1308f709627bf280)
