### ISSUE TITLE
Choose an operating system

### ISSUE THREAD

**Issue by Andymulator** [adespoton/utmconfigs#5]
So, the problem is, I have the MacOS Mount. Lion installation.iso at the ready, and I followed your direction.
Downloaded the pre-configured.utm file and just inserted the iso to the CD/DVD section.
However, when I boot up my VM, and reach the choosing-the-operating-system screen, it cannot detect the .iso filie.
Any solutions???

**Comment by adespoton** [comment]
You saved the InstallESD.dmg as a disk image?

I just re-did this, and it worked fine.  "Install OS X Mountain Lion" is in my #1 slot on the boot list.

You may find that the signing certificate has expired, in which case you'll need to temporarily change the system clock back to complete the install.  But with a correctly written iso, it should show up in the boot list.
