### ISSUE TITLE
Cannot install macOS Mojave 10.4

### ISSUE THREAD

**Issue by sergio-nunez-meneses** [adespoton/utmconfigs#8]
# Environment

MBP M1 Monterey 12.6

UTM 3.2.4 (58)

# Details

I've downloaded [[the installer here](https://osxdaily.com/2018/09/29/download-full-macos-mojave-installer/)](https://osxdaily.com/2018/09/29/download-full-macos-mojave-installer/), converted it from `.app` into `.iso` with createinstalliso, and followed all the instructions listed in the `.utm` file. But when I'm up to finish the installation process...

<img width="1270" alt="Capture d’écran 2022-09-27 à 12 13 04" src="https://user-images.githubusercontent.com/63654322/192506712-606a8107-accb-4bb3-a6b1-caad2c31c21a.png">

Edit: ...it shows this error lines...

<img width="860" alt="Capture d’écran 2022-09-27 à 15 32 20" src="https://user-images.githubusercontent.com/63654322/192541037-43c04d57-09d1-49cc-b7bb-f50c81872673.png">

...and then it simply restarts.

<img width="1268" alt="Capture d’écran 2022-09-27 à 12 33 36" src="https://user-images.githubusercontent.com/63654322/192506802-71eebace-3c23-44ac-a21d-e603b298ff97.png">

Anyone experiencing the same issue?

**Comment by adespoton** [comment]
In your screenshot the installer is still selected on restart.  Did you follow the steps of ejecting the iso and selecting the regular macOS boot at the boot screen in your screenshot?-Em On Sep 27, 2022, at 3:53 AM, sergio núñez meneses ***@***.***> wrote:﻿
Environment
MBP M1 Monterey 12.6
UTM 3.2.4 (58)
Details
I've downloaded [the installer here](https://osxdaily.com/2018/09/29/download-full-macos-mojave-installer/), converted it from .app into .iso with createinstalliso, and followed all the instructions listed in the .utm file. But when I'm up to finish the installation process...

...it simply restarts.

Anyone experiencing the same issue?

**Comment by sergio-nunez-meneses** [comment]
Thank you for your reply, @adespoton.

I didn't eject the `.iso` file the first time. I did it now though, before this :

<img width="1270" alt="install" src="https://user-images.githubusercontent.com/63654322/192559995-37f5385d-71fe-4837-a8e9-38ba55e37b4a.png">

...but nothing happened. Should I do it before or after?

**Comment by adespoton** [comment]
After your installation is complete (it is a multi-stage process requiring a few reboots), you should shut down the VM, eject the disk image, and start it back up.  Then you’ll get to the boot options screen and should have the option to boot into macOS 10.14 or macOS 10.14.X Recovery.  The bootloader should automatically select macOS 10.14 after a short delay.-Em On Sep 27, 2022, at 7:55 AM, sergio núñez meneses ***@***.***> wrote:﻿
Thank you for your reply, @adespoton.
I didn't eject the .iso file the first time. I did it now though, before this :

...but nothing happened. Should I do it before or after?

**Comment by sergio-nunez-meneses** [comment]
I've carefully followed the steps you listed, but nothing seems to change. When I choose the regular macOS boot, it keeps getting stuck either here:

<img width="983" alt="stuck-1" src="https://user-images.githubusercontent.com/63654322/192878529-7f5a742c-8dd2-4f72-b6e6-c71e98436d19.png">

...or here:

<img width="982" alt="stuck-2" src="https://user-images.githubusercontent.com/63654322/192879778-410b10f0-1058-4140-9c17-a00a1fe64b4c.png">

**Comment by adespoton** [comment]
How long are you letting it sit there?  Could take 30 minutes or more.-Em On Sep 28, 2022, at 1:20 PM, sergio núñez meneses ***@***.***> wrote:﻿
I've carefully followed the steps you listed, but nothing seems to change. When I choose the regular macOS boot, it keeps getting stuck either here:

...or here:

**Comment by adespoton** [comment]
Hmm.  That should be long enough.  I’ll see if I can replicate your issue soon.-Em On Sep 29, 2022, at 6:41 AM, sergio núñez meneses ***@***.***> wrote:﻿
A couple of hours or so.

**Comment by sergio-nunez-meneses** [comment]
@adespoton, I kept trying to install macOS Mojave, unfortunately without success. However, I've managed to install macOS High Sierra using the same environment (MBP M1 Monterey 12.6, UTM 3.2.4 (58)), without retina mode.
Yet, performance is quite slow, graphics display is a bit flickering, and most of the time, the VM just freezes and needs a reboot. Would you have any clue on this?

At least, the installation process worked.

<img width="1273" alt="high-sierra" src="https://user-images.githubusercontent.com/63654322/200202239-780639a4-6a7f-4ddd-8d76-88b34763f706.png">

**Comment by adespoton** [comment]
You’re not going to get better speed; these are emulated, not virtualized, and graphics acceleration isn’t emulated at all.Only way to get it faster is with a faster host CPU or improvements in the QEMU X86-64 emulator core.-Em On Nov 6, 2022, at 3:56 PM, sergio núñez meneses ***@***.***> wrote:﻿
@adespoton, I kept trying to install macOS Mojave, unfortunately without success. However, I've managed to install macOS High Sierra using the same environment (MBP M1 Monterey 12.6, UTM 3.2.4 (58)), without retina mode.
Yet, performance is quite slow, graphics display is a bit flickering, and most of the time, the VM just freezes and needs a reboot. Would you have any clue on this?
At least, the installation process worked.

**Comment by GriffinDavidson** [comment]
I'm having the same issue with macOS Mojave and Catalina. [Mine also seem to get stuck right here](https://user-images.githubusercontent.com/63654322/192878529-7f5a742c-8dd2-4f72-b6e6-c71e98436d19.png) and just stops installing. It never progresses to the installing screen. macOS High Sierra did progress to the installing screen, and so far seems to be working fine
)
